x = input('Digite algo ')
print('O tipo primitivo desse valor é: ', type(x))
print('Ele é alfanumérico? ', x.isalnum())
print('Ele é decimal? ', x.isdecimal())
print('Ele é um título? ', x.istitle())
print('Ele é printável? ', x.isprintable())
print('Ele é 100% maiúsculo? ', x.isupper())